include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak-ci-initiative-sdk-extensions.yml'
    # ref: ''

flatpak:
  variables:
    MANIFEST_PATH: "org.gnome.Podcasts.Devel.json"
    FLATPAK_MODULE: "gnome-podcasts"
    MESON_ARGS: "-Dprofile=development"
    APP_ID: "org.gnome.Podcasts.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "org.gnome.Podcasts.Devel.flatpak"
  .extends: '.flatpak'

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  stage: ".pre"
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> podcasts-gtk/src/config.rs
    - echo -e "" >> podcasts-gtk/src/static_resource.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
