[package]
authors = ["Jordan Petridis <jpetridis@gnome.org>"]
name = "podcasts-data"
version = "0.1.0"
edition = "2018"

[dependencies]
ammonia = "3.1"
chrono = "0.4"
derive_builder = "0.9"
lazy_static = "1.4"
log = "0.4"
rayon = "1.3"
rfc822_sanitizer = "0.3"
rss = "1.9"
reqwest = { version = "0.10", features = ["blocking","json"] }
url = "2.1"
xdg = "2.2"
xml-rs = "0.8"
futures = "0.3"
hyper = "0.13"
http = "0.2"
hyper-tls = "0.4"
native-tls = "0.2"
num_cpus = "1.13"
anyhow = "1.0"
thiserror = "1.0"
base64 = "0.12"
mime_guess = "2.0"
tempdir = "0.3"
glob = "0.3"
crossbeam-channel = "0.4"

[dependencies.diesel]
features = ["sqlite", "r2d2"]
version = "1.4"

[dependencies.diesel_migrations]
features = ["sqlite"]
version = "1.4"

[dependencies.tokio]
features = ["rt-core", "rt-threaded", "macros"]
version = "0.2.21"

[dev-dependencies]
rand = "0.7"
tempdir = "0.3"
pretty_assertions = "0.6"
maplit = "1"
