[package]
authors = ["Jordan Petridis <jpetridis@gnome.org>"]
name = "podcasts-data"
version = "0.1.0"
edition = "2018"

[dependencies]
ammonia = "3.0.0"
chrono = "0.4.9"
derive_builder = "0.8.0"
lazy_static = "1.4.0"
log = "0.4.8"
rayon = "1.2.0"
rfc822_sanitizer = "0.3.3"
rss = "1.9.0"
url = "2.1.1"
xdg = "2.2.0"
xml-rs = "0.8.0"
futures = "0.3.4"
hyper = "0.13.2"
http = "0.2.0"
hyper-tls = "0.4.1"
native-tls = "0.2.3"
num_cpus = "1.10.1"
failure = "0.1.6"
failure_derive = "0.1.6"
base64 = "0.10.1"

[dependencies.diesel]
features = ["sqlite", "r2d2"]
version = "1.4.3"

[dependencies.diesel_migrations]
features = ["sqlite"]
version = "1.4.0"

[dependencies.tokio]
features = ["rt-core", "rt-threaded", "macros"]
version = "0.2.13"

[dev-dependencies]
rand = "0.7.2"
tempdir = "0.3.7"
pretty_assertions = "0.6.1"
maplit = "1.0.2"
