[package]
authors = ["Jordan Petridis <jpetridis@gnome.org>"]
name = "podcasts-data"
version = "0.1.0"
edition = "2018"

[dependencies]
ammonia = "3.1.0"
chrono = "0.4.13"
derive_builder = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
rayon = "1.3.1"
rfc822_sanitizer = "0.3.3"
rss = "1.9.0"
reqwest = { version = "0.10", features = ["blocking","json"] }
url = "2.1.1"
xdg = "2.2.0"
xml-rs = "0.8.3"
futures = "0.3.5"
hyper = "0.13.6"
http = "0.2.1"
hyper-tls = "0.4.3"
native-tls = "0.2.4"
num_cpus = "1.13.0"
anyhow = "1.0.31"
thiserror = "1.0.20"
base64 = "0.12.3"
mime_guess = "2.0.3"
tempdir = "0.3.7"
glob = "0.3.0"

[dependencies.diesel]
features = ["sqlite", "r2d2"]
version = "1.4.5"

[dependencies.diesel_migrations]
features = ["sqlite"]
version = "1.4.0"

[dependencies.tokio]
features = ["rt-core", "rt-threaded", "macros"]
version = "0.2.21"

[dev-dependencies]
rand = "0.7.3"
tempdir = "0.3.7"
pretty_assertions = "0.6.1"
maplit = "1.0.2"
