[package]
authors = ["Jordan Petridis <jpetridis@gnome.org>"]
name = "podcasts-data"
version = "0.1.0"
edition = "2018"

[dependencies]
ammonia = "3.0.0"
chrono = "0.4.9"
derive_builder = "0.7.1"
lazy_static = "1.3.0"
log = "0.4.6"
rayon = "1.0.3"
rfc822_sanitizer = "0.3.3"
rss = "1.7.0"
url = "2.1.0"
xdg = "2.2.0"
xml-rs = "0.8.0"
futures = "0.1.29"
hyper = "0.12.34"
http = "0.1.16"
tokio = "0.1.18"
hyper-tls = "0.3.2"
native-tls = "0.2.2"
num_cpus = "1.10.0"
failure = "0.1.5"
failure_derive = "0.1.5"
base64 = "0.10.1"

[dependencies.diesel]
features = ["sqlite", "r2d2"]
version = "1.4.2"

[dependencies.diesel_migrations]
features = ["sqlite"]
version = "1.4.0"

[dev-dependencies]
rand = "0.7.0"
tempdir = "0.3.7"
pretty_assertions = "0.6.1"
maplit = "1.0.1"
