[package]
authors = ["Jordan Petridis <jpetridis@gnome.com>"]
name = "podcasts-gtk"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.11"
crossbeam-channel = "0.3.9"
gdk = "0.12.1"
gdk-pixbuf = "0.8.0"
gobject-sys = "0.9.1"
glib-sys = "0.9.1"
gst = { version = "0.15.7", package = "gstreamer" }
gst-player = { version = "0.15.5", package = "gstreamer-player" }
humansize = "1.1.0"
lazy_static = "1.4.0"
log = "0.4.8"
loggerv = "0.7.2"
open = "1.4.0"
rayon = "1.3.1"
url = "2.1.0"
failure = "0.1.8"
failure_derive = "0.1.8"
fragile = "1.0.0"
regex = "1.3.9"
reqwest = "0.9.22"
serde_json = "1.0.55"
html2text = "0.1.12"
mpris-player = "0.5.0"
pango = "0.8.0"
glib = "0.9.3"

[dependencies.gettext-rs]
git = "https://github.com/danigm/gettext-rs"
branch = "no-gettext"
features = ["gettext-system"]

[dependencies.gio]
features = ["v2_50"]
version = "0.8.1"

[dependencies.gtk]
features = ["v3_24"]
version = "0.8.1"

[dependencies.libhandy]
version = "0.5.0"
features = [ "v0_0_10"]

# [dependencies.mpris-player]
# version = "0.4.0"
# git = "https://gitlab.gnome.org/World/Rust/mpris-player"

[dependencies.podcasts-data]
path = "../podcasts-data"

[dev-dependencies]
pretty_assertions = "0.6.1"
