[package]
authors = ["Jordan Petridis <jpetridis@gnome.com>"]
name = "podcasts-gtk"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.13"
crossbeam-channel = "0.3.9"
gdk = "0.13.0"
gdk-pixbuf = "0.9.0"
gst = { version = "0.16.0", package = "gstreamer" }
gst-player = { version = "0.16.0", package = "gstreamer-player" }
humansize = "1.1.0"
lazy_static = "1.4.0"
log = "0.4.8"
loggerv = "0.7.2"
open = "1.4.0"
rayon = "1.3.1"
url = "2.1.1"
anyhow = "1.0.31"
fragile = "1.0.0"
regex = "1.3.9"
reqwest = { version = "0.10", features = ["blocking","json"] }
serde_json = "1.0.56"
html2text = "0.1.12"
glib = "0.10.1"

[dependencies.gettext-rs]
git = "https://github.com/danigm/gettext-rs"
branch = "no-gettext"
features = ["gettext-system"]

[dependencies.gio]
features = ["v2_50"]
version = "0.9.0"

[dependencies.gtk]
features = ["v3_24"]
version = "0.9.0"

[dependencies.libhandy]
version = "0.6.0"
features = [ "v0_0_12"]

[dependencies.mpris-player]
# git = "https://gitlab.gnome.org/World/Rust/mpris-player.git"
# rev = "42d17a430cd0df2ee03f97f65bbe5a0992b9f868"
version = "0.6"

[dependencies.podcasts-data]
path = "../podcasts-data"

[dev-dependencies]
pretty_assertions = "0.6.1"
